este proyecto pretende resolver un puzzle deslisante de 3x3

In [11]:
import numpy as np
from queue import PriorityQueue

def lista_hijos(x):
    x = np.array(x).reshape((3,3))
    set1 = set()
    a, b = np.where(x==0)
    a = a[0]
    b = b[0]
    if a != 0:
        # mueve hacia arriba
        y = x.copy()
        tmp = y[a,b]
        y[a,b] = y[a-1,b]
        y[a-1,b] = tmp
        set1.add(tuple(y.reshape(-1)))
    if a != x.shape[0]-1:
        # mueve hacia abajo
        y = x.copy()
        tmp = y[a,b]
        y[a,b] = y[a+1,b]
        y[a+1,b] = tmp
        set1.add(tuple(y.reshape(-1)))
    if b != 0:
        # mueve hacia la izquierda
        y = x.copy()
        tmp = y[a,b]
        y[a,b] = y[a,b-1]
        y[a,b-1] = tmp
        set1.add(tuple(y.reshape(-1)))
    if b != x.shape[1]-1:
        # mueba hacia la derecha
        y = x.copy()
        tmp = y[a,b]
        y[a,b] = y[a,b+1]
        y[a,b+1] = tmp
        set1.add(tuple(y.reshape(-1)))
    return set1

def ucs( start, goal):
    start = tuple(start.reshape(-1))
    goal = tuple(goal.reshape(-1))
    visited = []
    path = []
    fringe = PriorityQueue()
    fringe.put((0, start, path, visited))

    while not fringe.empty():
        depth, current_node, path, visited = fringe.get()

        if current_node == goal:
            return path + [current_node]

        visited = visited + [current_node]

        for node in lista_hijos(current_node):
            if node not in visited:
                if node == goal:
                    return path + [node]
                depth_of_node = len(path)
                fringe.put((-depth_of_node, node, path + [node], visited))

    return path

la o es el punto de origen del puzzle (usualmente empiza desordenado) y la d es el punto de destino (es usulmente el puzzle ordenado y completado)

In [14]:
o = np.array([[2,8,3],[1,6,4],[7,0,5]])
d = np.array([[1,2,3],[8,0,4],[7,6,5]])
path = ucs(o,d)
print("path", path) 

path [(2, 8, 3, 1, 0, 4, 7, 6, 5), (2, 0, 3, 1, 8, 4, 7, 6, 5), (0, 2, 3, 1, 8, 4, 7, 6, 5), (1, 2, 3, 0, 8, 4, 7, 6, 5), (1, 2, 3, 8, 0, 4, 7, 6, 5)]


In [15]:
def pasos(path):
    count = 0
    for step in path:
        print("numero:", count)
        matriz = np.array(step)
        print(matriz.reshape(3,3))
        count+=1

el programa seguira paso a paso el como resolver el puzzle

In [16]:
print(pasos(path))

numero: 0
[[2 8 3]
 [1 0 4]
 [7 6 5]]
numero: 1
[[2 0 3]
 [1 8 4]
 [7 6 5]]
numero: 2
[[0 2 3]
 [1 8 4]
 [7 6 5]]
numero: 3
[[1 2 3]
 [0 8 4]
 [7 6 5]]
numero: 4
[[1 2 3]
 [8 0 4]
 [7 6 5]]
None
